name: GitHub Script Example

on:
  # schedule:
  #   # - cron: 55 5 * * * # â€œAt every 05:55.â€
  #   - cron: "*/15 * * * *" # â€œAt every 15th minute.â€
  push:
    branches:
      - main
      - master

jobs:
  updates:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "ğŸ¥°"
          result-encoding: string
      - name: Get Result
        run: echo "${{steps.set-result.outputs.result}}"

      - name: View Context Attributes
        uses: actions/github-script@v6
        with:
          script: console.log(context)
