name: Random Flags

on:
  schedule:
    - cron: 0 */12 * * * # â€œAt minute 0 past every 12th hour.â€
  push:
    branches:
      - main

jobs:
  updates:
    name: Random Flags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
      - run: |
          #!/usr/bin/env bash

          declare -A emojiFlags

          emojiFlags["Ascension Island"]='ğŸ‡¦ğŸ‡¨'
          emojiFlags["Andorra"]='ğŸ‡¦ğŸ‡©'
          emojiFlags["United Arab Emirates"]='ğŸ‡¦ğŸ‡ª'
          emojiFlags["Afghanistan"]='ğŸ‡¦ğŸ‡«'
          emojiFlags["Antigua & Barbuda"]='ğŸ‡¦ğŸ‡¬'
          emojiFlags["Anguilla"]='ğŸ‡¦ğŸ‡®'
          emojiFlags["Albania"]='ğŸ‡¦ğŸ‡±'
          emojiFlags["Armenia"]='ğŸ‡¦ğŸ‡²'
          emojiFlags["Angola"]='ğŸ‡¦ğŸ‡´'
          emojiFlags["Antarctica"]='ğŸ‡¦ğŸ‡¶'
          emojiFlags["Argentina"]='ğŸ‡¦ğŸ‡·'
          emojiFlags["American Samoa"]='ğŸ‡¦ğŸ‡¸'
          emojiFlags["Austria"]='ğŸ‡¦ğŸ‡¹'
          emojiFlags["Australia"]='ğŸ‡¦ğŸ‡º'
          emojiFlags["Aruba"]='ğŸ‡¦ğŸ‡¼'
          emojiFlags["Ã…land Islands"]='ğŸ‡¦ğŸ‡½'
          emojiFlags["Azerbaijan"]='ğŸ‡¦ğŸ‡¿'
          emojiFlags["Bosnia & Herzegovina"]='ğŸ‡§ğŸ‡¦'
          emojiFlags["Barbados"]='ğŸ‡§ğŸ‡§'
          emojiFlags["Bangladesh"]='ğŸ‡§ğŸ‡©'
          emojiFlags["Belgium"]='ğŸ‡§ğŸ‡ª'
          emojiFlags["Burkina Faso"]='ğŸ‡§ğŸ‡«'
          emojiFlags["Bulgaria"]='ğŸ‡§ğŸ‡¬'
          emojiFlags["Bahrain"]='ğŸ‡§ğŸ‡­'
          emojiFlags["Burundi"]='ğŸ‡§ğŸ‡®'
          emojiFlags["Benin"]='ğŸ‡§ğŸ‡¯'
          emojiFlags["St. BarthÃ©lemy"]='ğŸ‡§ğŸ‡±'
          emojiFlags["Bermuda"]='ğŸ‡§ğŸ‡²'
          emojiFlags["Brunei"]='ğŸ‡§ğŸ‡³'
          emojiFlags["Bolivia"]='ğŸ‡§ğŸ‡´'
          emojiFlags["Caribbean Netherlands"]='ğŸ‡§ğŸ‡¶'
          emojiFlags["Brazil"]='ğŸ‡§ğŸ‡·'
          emojiFlags["Bahamas"]='ğŸ‡§ğŸ‡¸'
          emojiFlags["Bhutan"]='ğŸ‡§ğŸ‡¹'
          emojiFlags["Bouvet Island"]='ğŸ‡§ğŸ‡»'
          emojiFlags["Botswana"]='ğŸ‡§ğŸ‡¼'
          emojiFlags["Belarus"]='ğŸ‡§ğŸ‡¾'
          emojiFlags["Belize"]='ğŸ‡§ğŸ‡¿'
          emojiFlags["Canada"]='ğŸ‡¨ğŸ‡¦'
          emojiFlags["Cocos (Keeling) Islands"]='ğŸ‡¨ğŸ‡¨'
          emojiFlags["Congo - Kinshasa"]='ğŸ‡¨ğŸ‡©'
          emojiFlags["Central African Republic"]='ğŸ‡¨ğŸ‡«'
          emojiFlags["Congo - Brazzaville"]='ğŸ‡¨ğŸ‡¬'
          emojiFlags["Switzerland"]='ğŸ‡¨ğŸ‡­'
          emojiFlags["CÃ´te dâ€™Ivoire"]='ğŸ‡¨ğŸ‡®'
          emojiFlags["Cook Islands"]='ğŸ‡¨ğŸ‡°'
          emojiFlags["Chile"]='ğŸ‡¨ğŸ‡±'
          emojiFlags["Cameroon"]='ğŸ‡¨ğŸ‡²'
          emojiFlags["China"]='ğŸ‡¨ğŸ‡³'
          emojiFlags["Colombia"]='ğŸ‡¨ğŸ‡´'
          emojiFlags["Clipperton Island"]='ğŸ‡¨ğŸ‡µ'
          emojiFlags["Costa Rica"]='ğŸ‡¨ğŸ‡·'
          emojiFlags["Cuba"]='ğŸ‡¨ğŸ‡º'
          emojiFlags["Cape Verde"]='ğŸ‡¨ğŸ‡»'
          emojiFlags["CuraÃ§ao"]='ğŸ‡¨ğŸ‡¼'
          emojiFlags["Christmas Island"]='ğŸ‡¨ğŸ‡½'
          emojiFlags["Cyprus"]='ğŸ‡¨ğŸ‡¾'
          emojiFlags["Czechia"]='ğŸ‡¨ğŸ‡¿'
          emojiFlags["Germany"]='ğŸ‡©ğŸ‡ª'
          emojiFlags["Diego Garcia"]='ğŸ‡©ğŸ‡¬'
          emojiFlags["Djibouti"]='ğŸ‡©ğŸ‡¯'
          emojiFlags["Denmark"]='ğŸ‡©ğŸ‡°'
          emojiFlags["Dominica"]='ğŸ‡©ğŸ‡²'
          emojiFlags["Dominican Republic"]='ğŸ‡©ğŸ‡´'
          emojiFlags["Algeria"]='ğŸ‡©ğŸ‡¿'
          emojiFlags["Ceuta & Melilla"]='ğŸ‡ªğŸ‡¦'
          emojiFlags["Ecuador"]='ğŸ‡ªğŸ‡¨'
          emojiFlags["Estonia"]='ğŸ‡ªğŸ‡ª'
          emojiFlags["Egypt"]='ğŸ‡ªğŸ‡¬'
          emojiFlags["Western Sahara"]='ğŸ‡ªğŸ‡­'
          emojiFlags["Eritrea"]='ğŸ‡ªğŸ‡·'
          emojiFlags["Spain"]='ğŸ‡ªğŸ‡¸'
          emojiFlags["Ethiopia"]='ğŸ‡ªğŸ‡¹'
          emojiFlags["European Union"]='ğŸ‡ªğŸ‡º'
          emojiFlags["Finland"]='ğŸ‡«ğŸ‡®'
          emojiFlags["Fiji"]='ğŸ‡«ğŸ‡¯'
          emojiFlags["Falkland Islands"]='ğŸ‡«ğŸ‡°'
          emojiFlags["Micronesia"]='ğŸ‡«ğŸ‡²'
          emojiFlags["Faroe Islands"]='ğŸ‡«ğŸ‡´'
          emojiFlags["France"]='ğŸ‡«ğŸ‡·'
          emojiFlags["Gabon"]='ğŸ‡¬ğŸ‡¦'
          emojiFlags["United Kingdom"]='ğŸ‡¬ğŸ‡§'
          emojiFlags["Grenada"]='ğŸ‡¬ğŸ‡©'
          emojiFlags["Georgia"]='ğŸ‡¬ğŸ‡ª'
          emojiFlags["French Guiana"]='ğŸ‡¬ğŸ‡«'
          emojiFlags["Guernsey"]='ğŸ‡¬ğŸ‡¬'
          emojiFlags["Ghana"]='ğŸ‡¬ğŸ‡­'
          emojiFlags["Gibraltar"]='ğŸ‡¬ğŸ‡®'
          emojiFlags["Greenland"]='ğŸ‡¬ğŸ‡±'
          emojiFlags["Gambia"]='ğŸ‡¬ğŸ‡²'
          emojiFlags["Guinea"]='ğŸ‡¬ğŸ‡³'
          emojiFlags["Guadeloupe"]='ğŸ‡¬ğŸ‡µ'
          emojiFlags["Equatorial Guinea"]='ğŸ‡¬ğŸ‡¶'
          emojiFlags["Greece"]='ğŸ‡¬ğŸ‡·'
          emojiFlags["South Georgia & South Sandwich Islands"]='ğŸ‡¬ğŸ‡¸'
          emojiFlags["Guatemala"]='ğŸ‡¬ğŸ‡¹'
          emojiFlags["Guam"]='ğŸ‡¬ğŸ‡º'
          emojiFlags["Guinea-Bissau"]='ğŸ‡¬ğŸ‡¼'
          emojiFlags["Guyana"]='ğŸ‡¬ğŸ‡¾'
          emojiFlags["Hong Kong SAR China"]='ğŸ‡­ğŸ‡°'
          emojiFlags["Heard & McDonald Islands"]='ğŸ‡­ğŸ‡²'
          emojiFlags["Honduras"]='ğŸ‡­ğŸ‡³'
          emojiFlags["Croatia"]='ğŸ‡­ğŸ‡·'
          emojiFlags["Haiti"]='ğŸ‡­ğŸ‡¹'
          emojiFlags["Hungary"]='ğŸ‡­ğŸ‡º'
          emojiFlags["Canary Islands"]='ğŸ‡®ğŸ‡¨'
          emojiFlags["Indonesia"]='ğŸ‡®ğŸ‡©'
          emojiFlags["Ireland"]='ğŸ‡®ğŸ‡ª'
          emojiFlags["Israel"]='ğŸ‡®ğŸ‡±'
          emojiFlags["Isle of Man"]='ğŸ‡®ğŸ‡²'
          emojiFlags["India"]='ğŸ‡®ğŸ‡³'
          emojiFlags["British Indian Ocean Territory"]='ğŸ‡®ğŸ‡´'
          emojiFlags["Iraq"]='ğŸ‡®ğŸ‡¶'
          emojiFlags["Iran"]='ğŸ‡®ğŸ‡·'
          emojiFlags["Iceland"]='ğŸ‡®ğŸ‡¸'
          emojiFlags["Italy"]='ğŸ‡®ğŸ‡¹'
          emojiFlags["Jersey"]='ğŸ‡¯ğŸ‡ª'
          emojiFlags["Jamaica"]='ğŸ‡¯ğŸ‡²'
          emojiFlags["Jordan"]='ğŸ‡¯ğŸ‡´'
          emojiFlags["Japan"]='ğŸ‡¯ğŸ‡µ'
          emojiFlags["Kenya"]='ğŸ‡°ğŸ‡ª'
          emojiFlags["Kyrgyzstan"]='ğŸ‡°ğŸ‡¬'
          emojiFlags["Cambodia"]='ğŸ‡°ğŸ‡­'
          emojiFlags["Kiribati"]='ğŸ‡°ğŸ‡®'
          emojiFlags["Comoros"]='ğŸ‡°ğŸ‡²'
          emojiFlags["St. Kitts & Nevis"]='ğŸ‡°ğŸ‡³'
          emojiFlags["North Korea"]='ğŸ‡°ğŸ‡µ'
          emojiFlags["South Korea"]='ğŸ‡°ğŸ‡·'
          emojiFlags["Kuwait"]='ğŸ‡°ğŸ‡¼'
          emojiFlags["Cayman Islands"]='ğŸ‡°ğŸ‡¾'
          emojiFlags["Kazakhstan"]='ğŸ‡°ğŸ‡¿'
          emojiFlags["Laos"]='ğŸ‡±ğŸ‡¦'
          emojiFlags["Lebanon"]='ğŸ‡±ğŸ‡§'
          emojiFlags["St. Lucia"]='ğŸ‡±ğŸ‡¨'
          emojiFlags["Liechtenstein"]='ğŸ‡±ğŸ‡®'
          emojiFlags["Sri Lanka"]='ğŸ‡±ğŸ‡°'
          emojiFlags["Liberia"]='ğŸ‡±ğŸ‡·'
          emojiFlags["Lesotho"]='ğŸ‡±ğŸ‡¸'
          emojiFlags["Lithuania"]='ğŸ‡±ğŸ‡¹'
          emojiFlags["Luxembourg"]='ğŸ‡±ğŸ‡º'
          emojiFlags["Latvia"]='ğŸ‡±ğŸ‡»'
          emojiFlags["Libya"]='ğŸ‡±ğŸ‡¾'
          emojiFlags["Morocco"]='ğŸ‡²ğŸ‡¦'
          emojiFlags["Monaco"]='ğŸ‡²ğŸ‡¨'
          emojiFlags["Moldova"]='ğŸ‡²ğŸ‡©'
          emojiFlags["Montenegro"]='ğŸ‡²ğŸ‡ª'
          emojiFlags["St. Martin"]='ğŸ‡²ğŸ‡«'
          emojiFlags["Madagascar"]='ğŸ‡²ğŸ‡¬'
          emojiFlags["Marshall Islands"]='ğŸ‡²ğŸ‡­'
          emojiFlags["North Macedonia"]='ğŸ‡²ğŸ‡°'
          emojiFlags["Mali"]='ğŸ‡²ğŸ‡±'
          emojiFlags["Myanmar (Burma)"]='ğŸ‡²ğŸ‡²'
          emojiFlags["Mongolia"]='ğŸ‡²ğŸ‡³'
          emojiFlags["Macao Sar China"]='ğŸ‡²ğŸ‡´'
          emojiFlags["Northern Mariana Islands"]='ğŸ‡²ğŸ‡µ'
          emojiFlags["Martinique"]='ğŸ‡²ğŸ‡¶'
          emojiFlags["Mauritania"]='ğŸ‡²ğŸ‡·'
          emojiFlags["Montserrat"]='ğŸ‡²ğŸ‡¸'
          emojiFlags["Malta"]='ğŸ‡²ğŸ‡¹'
          emojiFlags["Mauritius"]='ğŸ‡²ğŸ‡º'
          emojiFlags["Maldives"]='ğŸ‡²ğŸ‡»'
          emojiFlags["Malawi"]='ğŸ‡²ğŸ‡¼'
          emojiFlags["Mexico"]='ğŸ‡²ğŸ‡½'
          emojiFlags["Malaysia"]='ğŸ‡²ğŸ‡¾'
          emojiFlags["Mozambique"]='ğŸ‡²ğŸ‡¿'
          emojiFlags["Namibia"]='ğŸ‡³ğŸ‡¦'
          emojiFlags["New Caledonia"]='ğŸ‡³ğŸ‡¨'
          emojiFlags["Niger"]='ğŸ‡³ğŸ‡ª'
          emojiFlags["Norfolk Island"]='ğŸ‡³ğŸ‡«'
          emojiFlags["Nigeria"]='ğŸ‡³ğŸ‡¬'
          emojiFlags["Nicaragua"]='ğŸ‡³ğŸ‡®'
          emojiFlags["Netherlands"]='ğŸ‡³ğŸ‡±'
          emojiFlags["Norway"]='ğŸ‡³ğŸ‡´'
          emojiFlags["Nepal"]='ğŸ‡³ğŸ‡µ'
          emojiFlags["Nauru"]='ğŸ‡³ğŸ‡·'
          emojiFlags["Niue"]='ğŸ‡³ğŸ‡º'
          emojiFlags["New Zealand"]='ğŸ‡³ğŸ‡¿'
          emojiFlags["Oman"]='ğŸ‡´ğŸ‡²'
          emojiFlags["Panama"]='ğŸ‡µğŸ‡¦'
          emojiFlags["Peru"]='ğŸ‡µğŸ‡ª'
          emojiFlags["French Polynesia"]='ğŸ‡µğŸ‡«'
          emojiFlags["Papua New Guinea"]='ğŸ‡µğŸ‡¬'
          emojiFlags["Philippines"]='ğŸ‡µğŸ‡­'
          emojiFlags["Pakistan"]='ğŸ‡µğŸ‡°'
          emojiFlags["Poland"]='ğŸ‡µğŸ‡±'
          emojiFlags["St. Pierre & Miquelon"]='ğŸ‡µğŸ‡²'
          emojiFlags["Pitcairn Islands"]='ğŸ‡µğŸ‡³'
          emojiFlags["Puerto Rico"]='ğŸ‡µğŸ‡·'
          emojiFlags["Palestinian Territories"]='ğŸ‡µğŸ‡¸'
          emojiFlags["Portugal"]='ğŸ‡µğŸ‡¹'
          emojiFlags["Palau"]='ğŸ‡µğŸ‡¼'
          emojiFlags["Paraguay"]='ğŸ‡µğŸ‡¾'
          emojiFlags["Qatar"]='ğŸ‡¶ğŸ‡¦'
          emojiFlags["RÃ©union"]='ğŸ‡·ğŸ‡ª'
          emojiFlags["Romania"]='ğŸ‡·ğŸ‡´'
          emojiFlags["Serbia"]='ğŸ‡·ğŸ‡¸'
          emojiFlags["Russia"]='ğŸ‡·ğŸ‡º'
          emojiFlags["Rwanda"]='ğŸ‡·ğŸ‡¼'
          emojiFlags["Saudi Arabia"]='ğŸ‡¸ğŸ‡¦'
          emojiFlags["Solomon Islands"]='ğŸ‡¸ğŸ‡§'
          emojiFlags["Seychelles"]='ğŸ‡¸ğŸ‡¨'
          emojiFlags["Sudan"]='ğŸ‡¸ğŸ‡©'
          emojiFlags["Sweden"]='ğŸ‡¸ğŸ‡ª'
          emojiFlags["Singapore"]='ğŸ‡¸ğŸ‡¬'
          emojiFlags["St. Helena"]='ğŸ‡¸ğŸ‡­'
          emojiFlags["Slovenia"]='ğŸ‡¸ğŸ‡®'
          emojiFlags["Svalbard & Jan Mayen"]='ğŸ‡¸ğŸ‡¯'
          emojiFlags["Slovakia"]='ğŸ‡¸ğŸ‡°'
          emojiFlags["Sierra Leone"]='ğŸ‡¸ğŸ‡±'
          emojiFlags["San Marino"]='ğŸ‡¸ğŸ‡²'
          emojiFlags["Senegal"]='ğŸ‡¸ğŸ‡³'
          emojiFlags["Somalia"]='ğŸ‡¸ğŸ‡´'
          emojiFlags["Suriname"]='ğŸ‡¸ğŸ‡·'
          emojiFlags["South Sudan"]='ğŸ‡¸ğŸ‡¸'
          emojiFlags["SÃ£o TomÃ© & PrÃ­ncipe"]='ğŸ‡¸ğŸ‡¹'
          emojiFlags["El Salvador"]='ğŸ‡¸ğŸ‡»'
          emojiFlags["Sint Maarten"]='ğŸ‡¸ğŸ‡½'
          emojiFlags["Syria"]='ğŸ‡¸ğŸ‡¾'
          emojiFlags["Eswatini"]='ğŸ‡¸ğŸ‡¿'
          emojiFlags["Tristan Da Cunha"]='ğŸ‡¹ğŸ‡¦'
          emojiFlags["Turks & Caicos Islands"]='ğŸ‡¹ğŸ‡¨'
          emojiFlags["Chad"]='ğŸ‡¹ğŸ‡©'
          emojiFlags["French Southern Territories"]='ğŸ‡¹ğŸ‡«'
          emojiFlags["Togo"]='ğŸ‡¹ğŸ‡¬'
          emojiFlags["Thailand"]='ğŸ‡¹ğŸ‡­'
          emojiFlags["Tajikistan"]='ğŸ‡¹ğŸ‡¯'
          emojiFlags["Tokelau"]='ğŸ‡¹ğŸ‡°'
          emojiFlags["Timor-Leste"]='ğŸ‡¹ğŸ‡±'
          emojiFlags["Turkmenistan"]='ğŸ‡¹ğŸ‡²'
          emojiFlags["Tunisia"]='ğŸ‡¹ğŸ‡³'
          emojiFlags["Tonga"]='ğŸ‡¹ğŸ‡´'
          emojiFlags["Turkey"]='ğŸ‡¹ğŸ‡·'
          emojiFlags["Trinidad & Tobago"]='ğŸ‡¹ğŸ‡¹'
          emojiFlags["Tuvalu"]='ğŸ‡¹ğŸ‡»'
          emojiFlags["Taiwan"]='ğŸ‡¹ğŸ‡¼'
          emojiFlags["Tanzania"]='ğŸ‡¹ğŸ‡¿'
          emojiFlags["Ukraine"]='ğŸ‡ºğŸ‡¦'
          emojiFlags["Uganda"]='ğŸ‡ºğŸ‡¬'
          emojiFlags["U.S. Outlying Islands"]='ğŸ‡ºğŸ‡²'
          emojiFlags["United Nations"]='ğŸ‡ºğŸ‡³'
          emojiFlags["United States"]='ğŸ‡ºğŸ‡¸'
          emojiFlags["Uruguay"]='ğŸ‡ºğŸ‡¾'
          emojiFlags["Uzbekistan"]='ğŸ‡ºğŸ‡¿'
          emojiFlags["Vatican City"]='ğŸ‡»ğŸ‡¦'
          emojiFlags["St. Vincent & Grenadines"]='ğŸ‡»ğŸ‡¨'
          emojiFlags["Venezuela"]='ğŸ‡»ğŸ‡ª'
          emojiFlags["British Virgin Islands"]='ğŸ‡»ğŸ‡¬'
          emojiFlags["U.S. Virgin Islands"]='ğŸ‡»ğŸ‡®'
          emojiFlags["Vietnam"]='ğŸ‡»ğŸ‡³'
          emojiFlags["Vanuatu"]='ğŸ‡»ğŸ‡º'
          emojiFlags["Wallis & Futuna"]='ğŸ‡¼ğŸ‡«'
          emojiFlags["Samoa"]='ğŸ‡¼ğŸ‡¸'
          emojiFlags["Kosovo"]='ğŸ‡½ğŸ‡°'
          emojiFlags["Yemen"]='ğŸ‡¾ğŸ‡ª'
          emojiFlags["Mayotte"]='ğŸ‡¾ğŸ‡¹'
          emojiFlags["South Africa"]='ğŸ‡¿ğŸ‡¦'
          emojiFlags["Zambia"]='ğŸ‡¿ğŸ‡²'
          emojiFlags["Zimbabwe"]='ğŸ‡¿ğŸ‡¼'
          emojiFlags["England"]='ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿'
          emojiFlags["Scotland"]='ğŸ´ó §ó ¢ó ³ó £ó ´ó ¿'
          emojiFlags["Wales"]='ğŸ´ó §ó ¢ó ·ó ¬ó ³ó ¿'

          echo "${emojiFlags["Malaysia"]}"
          echo "${emojiFlags["Norway"]}"

          for flag in "${!emojiFlags[@]}"; do
              echo "$flag - ${emojiFlags[$flag]}"
          done
        shell: bash
