name: Update Weather

on:
  schedule:
    - cron: 0 */3 * * * # “At minute 0 past every 3rd hour.”
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual trigger to run workflow.

jobs:
  updates:
    name: Update Weather
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 24
      - run: npm install --global yarn
      - run: |
          # https://stackoverflow.com/a/70541151
          yarn add \
            luxon \
            mustache \
            node-fetch@2.6.1 \
            xml-js \
            --flat \
            --no-lockfile \
            --verbose
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          OPEN_WEATHER_KEY: ${{secrets.OPEN_WEATHER_KEY}}
        with:
          github-token: ${{ secrets.USER_SCOPE }}
          script: |
            const script = require('.github/workflows/update-weather.js')
            console.log(await script({github, context, core}))
      - run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit --message 'chore(workflows): update weather data'
          git push
