# https://github.com/jasonetco/jasonetco/blob/master/.github/workflows/daily-updates.yml

name: Update Status

on:
  schedule:
    - cron: 55 5 * * * # “At every 05:55.”
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual trigger to run workflow.

jobs:
  updates:
    name: Update Status
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.USER_SCOPE }}
          script: |
            const script = require('.github/workflows/update-status.js')
            console.log(await script({github, context, core}))
